### ISSUE TITLE
focus should return to origin element when modal is closed

### ISSUE THREAD

**Issue by MelSumner** [simplabs/ember-promise-modals#2]
## Environment 
This happens on a PC in both Firefox and Chrome. 

## What I expect to happen
`ESC` and the close button should both close the modal and return focus to the element that opened the modal. 

## What happens
- When I press `ESC` and close the modal, the focus (correctly) returns to the button that opened the modal. 
- When I interact with the "close" button to close the modal, focus is not returned to the button that opened the modal.

**Comment by Turbo87** [comment]
hmm, interesting. do you think we're using the `focus-trap` library in a wrong way? I would have expected that to take care of this case 🤔

**Comment by pichfl** [comment]
I am able replicate this. The problem is not inside `focus-trap`, but related to how we close the modal (by removing it from the DOM). 

Not sure how this works in `focus-trap`, but I guess we can use the same mechanism it uses to restore focus to do so as well when we close the modal "manually".

**Comment by pichfl** [comment]
This was fixed by the Release of v1.0.0

**Comment by nickschot** [comment]
@pichfl we might want to double check if we need to properly handle multiple modals. focus-trap appears to have a `pause` function for this use case.
