### ISSUE TITLE
Decorator being a barrier to be able to use it with previous Ember versions

### ISSUE THREAD

**Issue by zeppelin** [simplabs/ember-promise-modals#434]
Converting `ember-promise-modals/modal` to a classic Ember Object would expand support to even earlier Ember versions. Huge codebases that struggle with updating could benefit greatly from EPM, and from what I observed, that part of the addon is not performance-critical.

We're patching EPM in our project at the moment. Do you accept PRs? :)

**Comment by pichfl** [comment]
We do accept PRs, this one sounds like a good idea 👍

**Comment by pichfl** [comment]
@zeppelin We want to move to the new v2 addon format with #479 which would require ember-auto-import v2 which in turn would also require Ember 3.4 or higher which matches the current support matrix of this addon. 

If you want to see this change before that, we are planning a last maintenance release before moving to the new format, so we could add this beforehand.

**Comment by pichfl** [comment]
We made attempts to do this but failed to provide a sensible test structure or matrix that spans this far in the Ember.js history. 

For anyone who wants to use this addon in legacy projects I can recommend re-creating and overriding the necessary files in your local project as a last resort until you can upgrade.
