### ISSUE TITLE
 Installing this package from Git using Yarn Berry v3.1.0 fails

### ISSUE THREAD

**Issue by pichfl** [simplabs/ember-promise-modals#562]
Unfortunately it seems this breaks installing this package from Git using Yarn Berry (at least v3.1.0 that I'm using) with `nodeLinker: node-modules`. Yarn says "Unsupported workflow", as it's seems like it doesn't understand pnpm lockfiles yet..

_Originally posted by @bitwolfe in https://github.com/simplabs/ember-promise-modals/issues/477#issuecomment-1070765262_

**Comment by pichfl** [comment]
I haven't worked with Yarn Berry before and am a bit puzzled by this as I would expect an install from git to use the `package.json` 🤔 

@bitwolfe could you provide a reproduction repository for this? We use pnpm in quite a few of our repositories and so far (and so do many other projects including much bigger ones such as Vue.js) and I haven't come across this issue yet.

**Comment by bitwolfe** [comment]
It's very puzzling indeed! I would have expected it to just go by the package.json since no yarn.lock is present, not just give up because there is a pnpm-lock present...

I've set up a simple repo for reproduction: https://github.com/bitwolfe/epm-git-yarn-repro

**Comment by pichfl** [comment]
Thanks for the reproduction, but I think this beyond the scope of this addon. We went with pnpm because it speeds up or CI and is what want to use for our packages going forward. A new version of promise modals which includes the latest fixes from master was released (with more fixes coming soon)

**Comment by bitwolfe** [comment]
That's fair. It does feel like it's either a bug in Yarn or some kind of configuration issue. Either way it behaves very strangely.

With there being a new version out which includes the fixes I needed, I no longer need to install directly from the git repo and can let this go for now.

**Comment by flying-sheep** [comment]
See https://github.com/yarnpkg/berry/issues/3169
