### ISSUE TITLE
Latest focus trap changes causes the modal response to be lost

### ISSUE THREAD

**Issue by bitwolfe** [simplabs/ember-promise-modals#565]
The recent change to how the focus trap is set up (PR #549) is causing issues when you expect the `close` action to return a value.

Specifically this change in the modal component on lines 103-105:
https://github.com/simplabs/ember-promise-modals/pull/549/files#diff-f1bdcfc6adc126290ecb2862332b13bf329fcd5a397b3ab6210de2911dc65d54L93-R105

Not passing in null here as it did before changes the behaviour in such a way that the focus trap's onDeactivate function calls closeModal again (without return value this time) and resolves the modal before the original `@close` action call has a chance to resolve with the return value that was passed in.

So currently, this happens:

1. A link in your modal calls `@close`
2. Internally the modal then calls closeModal(result) with the result passed to `@close`
3. This then runs focusTrap.deactivate() which immediately runs the onDeactivate function
4. closeModal() is called again, but without the passed in result this time.
5. The modal resolves with the undefined result before closeModal(result) from step 2 has a chance to resolve with its data.

Reverting lines 103-105 linked above makes it work properly again, though that probably breaks something else that the PR fixed?

Another workaround might be to set onDeactivate to null through the open() call or globally on the modals service, but that feels like it shouldn't be necessary.

**Comment by pichfl** [comment]
Thanks for reporting this. For some reason we were missing a test that verifies this. 

Resolved by #596
